[package]
name = "chatterbox-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
directories = "6"
futures = { version = "0.3", optional = true }
hound = "3"
ndarray = "0.17"
ort = "2.0.0-rc.13"
rand = "0.10"
reqwest = { version = "0.13", features = ["stream"], optional = true }
rubato = "5"
serde = { version = "1", features = ["derive"], optional = true }
serde_json = { version = "1", optional = true }
symphonia = "0.6"
thiserror = "2"
tokenizers = "0.23"
tokio = { version = "1", features = ["fs", "io-util"], optional = true }
url = { version = "2", optional = true }

[features]
default = ["common-audio-formats", "download"]

cuda = ["ort/cuda"]

mp3 = ["symphonia/mp3"]
mp4 = ["symphonia/aac", "symphonia/isomp4"]
common-audio-formats = ["mp3", "mp4"]
all-audio-formats = ["symphonia/all"]

download = ["dep:reqwest", "dep:futures", "dep:url", "dep:tokio"]

read-model-constants = ["dep:serde", "dep:serde_json"]

[dev-dependencies]
clap = { version = "4", features = ["derive"] }
