[package]
name = "chatterbox-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
directories = "6"
futures = { version = "0.3", optional = true }
half = { version = "2.1", features = ["num-traits"] }
hound = "3"
indicatif = "0.18"
ndarray = "0.17"
num-traits = "0.2"
ort = { version = "2.0.0-rc.13", features = ["half"] }
rand = "0.10"
reqwest = { version = "0.13", features = ["stream"], optional = true }
rubato = "5"
serde = { version = "1", features = ["derive"], optional = true }
symphonia = { version = "0.6", features = ["wav", "pcm"] }
thiserror = "2"
tokenizers = { version = "0.23", default-features = false, features = [
    "progressbar",
    "onig",
] }
tokio = { version = "1", features = ["fs", "io-util"], optional = true }
typed_floats = "1"
url = { version = "2", optional = true }

[features]
default = ["common-audio-formats"]

cuda = ["ort/cuda"]
# TODO: need to do manual export of ONNX models to get this to work for RT and RTX

mp3 = ["symphonia/mp3"]
mp4 = ["symphonia/aac", "symphonia/isomp4"]
common-audio-formats = ["mp3", "mp4"]
all-audio-formats = ["symphonia/all"]

download = ["dep:reqwest", "dep:futures", "dep:url", "dep:tokio"]

serde = ["dep:serde", "typed_floats/serde"]

custom-variants = []

[dev-dependencies]
clap = { version = "4", features = ["derive"] }
color-eyre = "0.6"
tokio = { version = "1", features = ["rt", "macros"] }
