version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries:
  - rust
  - softwareTerms
words:
  - byoo
  - chatterbot
  - cuda
  - dmanuel
  - Embedder
  - endoftext
  - isomp
  - Logits
  - ndarray
  - Onnx
  - reqwest
  - thiserror
ignoreWords: []
import: []
